### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (https://brands.home-assistant.io/homie/icon.png)

### ISSUE THREAD

**Issue by c64emulator** [elbowz/ha-homie#7]
The home assistant integration of homie works fine.
But looking at the DevTools Console I see error:
`Failed to load resource: the server responded with a status of 404 (https://brands.home-assistant.io/homie/icon.png)`
![homie_error404](https://user-images.githubusercontent.com/3796947/168443713-7566df68-daac-4edb-8f63-86d91044700e.PNG)
I have no idea where it is coming from and how to fix.

**Comment by elbowz** [comment]
Hi @c64emulator, 

 I guess this is related to the repository https://github.com/home-assistant/brands.
Fort what I read and understand, we should open a PR in that repo with the icon and logo of Homie component.
I'm quite busy, now....I hope to fix in next weeks. 

Anyway, It's a "cosmetic" feature, nothing of important or that limit the component functionality.

**Comment by spinza** [comment]
Please see PR:
https://github.com/home-assistant/brands/pull/4610

**Comment by spinza** [comment]
OK it's been merged.  Will see if it resolves images for me later.

**Comment by spinza** [comment]
Seems to be resolved.  Now getting images in the Home Assistant integration settings:
![image](https://github.com/elbowz/ha-homie/assets/3501598/bcfa71e9-b46a-4d20-b727-961fb2e3a927)

And in the device listing also:
![image](https://github.com/elbowz/ha-homie/assets/3501598/3e59407a-05ee-462c-af43-a2411b637b68)

I think this issue can be closed.
