### ISSUE TITLE
Error verifying configuration with ha-homie enabled in home assistant

### ISSUE THREAD

**Issue by keesma** [elbowz/ha-homie#8]
When I click verify configuration in developer tools I get the following error. I cannot find this error explained anywhere. Is this related to using this integration with a newer version of home assistant then it is originally developed with?

Component error: homie - cannot import name '_VALID_QOS_SCHEMA' from 'homeassistant.components.mqtt' (/usr/src/homeassistant/homeassistant/components/mqtt/__init__.py)

I am running homeassistant 2022.12.06

**Comment by keesma** [comment]
I am a little bit further now. I removed importing the constant  _VALID_QOS_SCHEMA 
and replaced it with: _VALID_QOS_SCHEMA = vol.All(vol.Coerce(int), vol.In([0, 1, 2]))

Now I got a message that there are new devices. When I try to add them then the following error is displayed: 
[%key:common::config_flow::abort::single_instance_allowed%]

**Comment by elbowz** [comment]
Hi @keesma, I'm quite busy in this period...I'll try to fix it during the christmas holliday.

My apologies for the long fixing time...thanks for your report! 

p.s. of course, feel free to provide a PR if you want

**Comment by elbowz** [comment]
Hi @keesma, 
 I have just pushed a fix for the reported issue (757a570767ae6e987e1ce065aa4dd8155566881f). 

Could you try it and report any issues?

**Comment by Qwertzl1** [comment]
Hi elbowz, thank you for the quick fix. Works good on by side,

**Comment by elbowz** [comment]
Thanks for your feedback @Qwertzl1 !
