### ISSUE TITLE
HomieNumber is overriding deprecated methods on an instance of NumberEntity

### ISSUE THREAD

**Issue by c64emulator** [elbowz/ha-homie#9]
When starting Home Assistant, I get the following message in the logfile:

```
Logger: homeassistant.components.number
Source: components/number/__init__.py:396
Integration: Nummer (documentation, issues)
First occurred: 12:13:39 (1 occurrences)
Last logged: 12:13:39

custom_components.homie.number::HomieNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be **unsupported from Home Assistant 2022.10**. Please report it to the custom integration author.
```

**Comment by elbowz** [comment]
Thanks for the issue reporting.

I think it is related to this change in HA:
 https://developers.home-assistant.io/blog/2022/06/14/number_entity_refactoring/

I'll fix it...hope soon :)

**Comment by elbowz** [comment]
Hi @c64emulator, 
the warning should be gone...let me know if you have any issues about this.

Ciao!

p.s. I have not increase the ha-homie version, try the master branch.

**Comment by c64emulator** [comment]
Hi,
yes, the warning is gone.
Great.
